import React from 'react';
import {Helmet} from 'react-helmet';
import {Link} from 'react-router-dom';
import {motion} from 'framer-motion';
import * as I from 'lucide-react';
import vikrant from '@/assets/Vikrant.jpeg';
import abhijeet from '@/assets/WhatsApp Image 2026-07-23 at 6.44.55 PM.jpeg';
import './AboutPage.css';

const principles=[['Clarity before code','ScanSearch','We solve the right problem before choosing the technology.'],['Built for real work','Workflow','Every decision respects the people who will use the system daily.'],['Progress in the open','PanelsTopLeft','Clear milestones, visible work and honest communication.'],['Security by default','ShieldCheck','Trust is designed into the architecture from day one.'],['Useful over impressive','CheckCircle2','We measure quality by adoption and outcomes, not complexity.'],['Always improving','RefreshCw','Launch is the beginning of a better feedback loop.']];
const timeline=[['01','Listen','Understand the operation and its constraints.'],['02','Frame','Define the smallest valuable change.'],['03','Build','Ship working software in clear phases.'],['04','Learn','Use evidence to improve what comes next.']];
const SafeIcon=({name,size=22})=>{const C=I[name]||I.Sparkles;return <C size={size}/>};
const reveal={initial:{opacity:0,y:25},whileInView:{opacity:1,y:0},viewport:{once:true,margin:'-70px'},transition:{duration:.55,ease:[.22,1,.36,1]}};

export default function AboutPage(){return <>
 <Helmet><title>Company | Alpenrose Digital Solutions</title><meta name="description" content="Meet Alpenrose Digital Solutions, a Patna-based technology company building practical AI, ERP, cloud and custom software systems."/><link rel="canonical" href="https://ards.in/about"/></Helmet>
 <section className="company-hero"><div className="company-grid"/><div className="company-glow cg-one"/><div className="company-glow cg-two"/><div className="site-shell company-hero-layout"><motion.div initial={{opacity:0,y:25}} animate={{opacity:1,y:0}}><span className="company-kicker"><i/> COMPANY · PATNA, INDIA</span><h1>Small enough to care.<br/><em>Built to think big.</em></h1><p>A product-minded team turning difficult operations into clear, dependable digital systems.</p><div className="company-actions"><Link to="/contact" className="btn btn-primary">Work with us <I.ArrowUpRight/></Link><a href="#company-story" className="btn btn-secondary">Our story <I.ArrowDown/></a></div></motion.div><motion.div className="company-graphic" initial={{opacity:0,scale:.92}} animate={{opacity:1,scale:1}} transition={{duration:.85}}><div className="company-core"><span>ARDS</span><b>Ideas into<br/>working systems</b><i/></div>{[['Think','Lightbulb','c1'],['Design','PenTool','c2'],['Engineer','Code2','c3'],['Support','Headphones','c4']].map(([x,icon,cls],index)=><motion.div className={'company-node '+cls} key={x} animate={{y:[0,index%2?9:-9,0]}} transition={{duration:4+index*.4,repeat:Infinity}}><span><SafeIcon name={icon}/></span><b>{x}</b></motion.div>)}<svg viewBox="0 0 600 500"><circle cx="300" cy="250" r="170"/><circle cx="300" cy="250" r="115"/><path d="M300 250L115 110M300 250L490 100M300 250L100 390M300 250L500 390"/></svg></motion.div><div className="company-hero-stats">{[['Patna','Home base'],['India','Primary market'],['24×7','Support'],['One team','End to end']].map(([v,l])=><div key={l}><b>{v}</b><span>{l}</span></div>)}</div></div></section>

 <section className="section company-story" id="company-story"><div className="site-shell"><motion.div className="story-heading" {...reveal}><span>WHY WE EXIST</span><h2>Technology should remove friction,<br/>not create more of it.</h2></motion.div><div className="story-layout"><motion.div className="story-copy" {...reveal}><p className="story-lead">ARDS began with a simple observation: organizations often know exactly what slows them down, but available software rarely fits the way they actually work.</p><p>We bring product thinking, design and engineering into one conversation. That keeps decisions closer to the problem and makes delivery easier to understand.</p><p>Our home is Patna. Our standards are global. The systems we create are practical enough for today and considered enough for what comes next.</p><div className="story-signature"><span>ARDS</span><div><b>Alpenrose Digital Solutions</b><small>Empowering businesses through innovative digital transformations</small></div></div></motion.div><motion.div className="story-panel" {...reveal}><div className="story-panel-top"><span>WHAT WE BRING TO THE TABLE</span><I.Sparkles/></div>{[['Product strategy','The reason behind every feature.'],['Experience design','Interfaces people can learn quickly.'],['Software engineering','Secure foundations that stay maintainable.'],['Long-term support','A partner after the launch.']].map(([x,p],i)=><div className="story-row" key={x}><b>0{i+1}</b><span><strong>{x}</strong><small>{p}</small></span><I.ArrowUpRight/></div>)}</motion.div></div></div></section>

 <section className="section principle-section"><div className="site-shell"><motion.div className="company-section-heading" {...reveal}><span>OUR PRINCIPLES</span><h2>The standards behind the work.</h2><p>Simple rules that keep projects focused and relationships healthy.</p></motion.div><div className="principle-grid">{principles.map(([title,icon,copy],index)=><motion.article key={title} {...reveal} transition={{...reveal.transition,delay:index*.05}}><small>{String(index+1).padStart(2,'0')}</small><span><SafeIcon name={icon}/></span><h3>{title}</h3><p>{copy}</p></motion.article>)}</div></div></section>

 <section className="section leadership-section"><div className="site-shell"><motion.div className="company-section-heading" {...reveal}><span>LEADERSHIP</span><h2>Accountable from the first conversation.</h2></motion.div><div className="leader-grid"><motion.article {...reveal}><div className="leader-image"><img src={vikrant} alt="Vikrant Mishra, Founder of Alpenrose Digital Solutions"/><div className="leader-shape"/></div><div className="leader-info"><span>FOUNDER</span><h3>Vikrant Mishra</h3><p>Guides company direction, client partnerships and the practical application of technology.</p><a href="https://in.linkedin.com/in/vikrant-mishra-5a55a1b7" target="_blank" rel="noopener noreferrer" aria-label="Vikrant Mishra on LinkedIn"><I.Linkedin/> Connect</a></div></motion.article><motion.article {...reveal} transition={{...reveal.transition,delay:.1}}><div className="leader-image"><img src={abhijeet} alt="Abhijeet M Mishra, Lead Software Engineer"/><div className="leader-shape"/></div><div className="leader-info"><span>LEAD SOFTWARE ENGINEER</span><h3>Abhijeet M Mishra</h3><p>Leads software architecture and engineering, turning complex requirements into secure, reliable products.</p><a href="https://www.linkedin.com/in/abhijeetmohanmishra" target="_blank" rel="noopener noreferrer" aria-label="Abhijeet M Mishra on LinkedIn"><I.Linkedin/> Connect</a></div></motion.article></div></div></section>

 <section className="section company-method"><div className="site-shell"><motion.div className="method-intro" {...reveal}><span>HOW WE WORK</span><h2>Direct. Visible.<br/>Always moving.</h2><p>No black boxes. Every phase produces something useful to review.</p></motion.div><div className="method-line">{timeline.map(([n,title,copy],i)=><motion.div key={title} {...reveal} transition={{...reveal.transition,delay:i*.08}}><b>{n}</b><i/><h3>{title}</h3><p>{copy}</p></motion.div>)}</div></div></section>

 <section className="company-belief"><div className="site-shell"><motion.div {...reveal}><I.Quote/><blockquote>“The best system is the one people trust enough to use every day.”</blockquote><span>OUR PRODUCT BELIEF</span></motion.div></div></section>
 <section className="company-cta"><div className="site-shell"><motion.div {...reveal}><span>BUILD WITH US</span><h2>Good problems deserve<br/>thoughtful teams.</h2><p>Tell us what is slowing you down—or what you want to make possible.</p><div><Link to="/contact" className="btn btn-primary">Start a conversation <I.ArrowUpRight/></Link><Link to="/contact" className="company-career"><I.Briefcase/> Explore careers</Link></div></motion.div></div></section>
 </>}
