import React, { useState } from 'react';
import { Helmet } from 'react-helmet';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import * as Icons from 'lucide-react';
import heroVisual from '@/assets/ards-enterprise-hero.png';
import CinematicHero from '@/components/CinematicHero';
import EnterpriseERP from '@/components/EnterpriseERP';
import { servicePath } from '@/data/serviceDetails';
import { industryPath } from '@/data/industryDetails';

const services = [
  ['Website Development','Globe2','Fast, accessible websites engineered to convert.'],['Application Development','PanelsTopLeft','Secure software built around your operations.'],['Mobile App Development','Smartphone','Native-quality experiences for every screen.'],['AI Automation','Bot','Intelligent workflows that remove repetitive work.'],['ERP Solutions','Blocks','One connected operating system for your business.'],['Cloud Solutions','CloudCog','Reliable cloud infrastructure that scales on demand.'],['Digital Marketing','Megaphone','Full-funnel campaigns focused on measurable growth.'],['SEO','Search','Build visibility and win high-intent organic traffic.'],['Cyber Security','ShieldCheck','Proactive protection for systems, people and data.'],['Web Hosting','Server','High-performance managed hosting with 99.9% uptime.'],['E-Commerce','ShoppingBag','Conversion-first storefronts and commerce operations.'],['Custom Software','Code2','Purpose-built platforms for complex business needs.'],['Attendance Management','ScanFace','Accurate, real-time attendance with smart insights.'],['Inventory','Boxes','Track stock, purchases and movement in real time.'],['HRMS','UsersRound','Simplify employee journeys from hire to payroll.'],['Hospital ERP','HeartPulse','Connected care, billing, pharmacy and administration.'],['School ERP','School','A complete digital campus for schools and parents.'],['College ERP','GraduationCap','Admissions to alumni, unified in one platform.'],['Manufacturing ERP','Factory','Plan production, materials, quality and dispatch.'],['Government Solutions','Landmark','Citizen-first digital systems built for scale.']
];
const industries = [['Education','GraduationCap'],['Healthcare','HeartPulse'],['Manufacturing','Factory'],['Government','Landmark'],['Retail','ShoppingCart'],['Hospitality','Hotel'],['NGO','HandHeart'],['Real Estate','Building2'],['Transportation','Truck'],['Sports Club','Trophy'],['Infrastructure','HardHat'],['Finance','ChartNoAxesCombined']];
const aiFeatures = [['Face Recognition','ScanFace'],['Workflow Automation','Workflow'],['AI Analytics','ChartSpline'],['Chatbots','MessagesSquare'],['OCR','ScanText'],['Document Automation','Files'],['Auto Reports','FileChartColumn'],['Smart Notifications','BellRing']];
const erpModules = ['Admissions','Attendance','Fees','Examination','HR','Payroll','Inventory','Finance','Library','Hostel','Transport','Canteen','ID Cards','Analytics','Reports','Download Center','Parent Portal','Teacher Portal','Student Portal'];
const why = [['Customized Solutions','SlidersHorizontal'],['Affordable Pricing','BadgeIndianRupee'],['Experienced Team','Users'],['Fast Delivery','Rocket'],['24×7 Support','Headphones'],['Secure Architecture','ShieldCheck'],['Cloud Ready','Cloud'],['AI Powered','Sparkles'],['Scalable','Expand'],['Modern Technology','Cpu']];
const stack = ['React','Next.js','FastAPI','Python','Node.js','Flutter','Android','iOS','MySQL','PostgreSQL','MongoDB','Docker','AWS','Azure','Cloud','GitHub','TensorFlow','OpenCV'];
const Reveal = ({children, className=''}) => <motion.div className={className} initial={{opacity:0,y:28}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-80px'}} transition={{duration:.55}}>{children}</motion.div>;
const Icon = ({name,size=22}) => { const C=Icons[name] || Icons.Sparkles; return <C size={size}/> };
const Heading = ({eyebrow,title,copy}) => <div className="section-heading"><span>{eyebrow}</span><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>;

export default function HomePage(){
 const [openFaq,setOpenFaq]=useState(0); const [employees,setEmployees]=useState(30); const [hours,setHours]=useState(8); const [demo,setDemo]=useState('Attendance'); const [showAllServices,setShowAllServices]=useState(false); const monthly=Math.round(employees*hours*250/60);
 return <>
  <Helmet><title>ARDS | AI, ERP & Digital Transformation Company in India</title><meta name="description" content="Alpenrose Digital Solutions builds AI automation, ERP, cloud, web and mobile solutions that help organizations work smarter and scale faster."/><meta property="og:title" content="Automate Your Business. Accelerate Your Growth."/><meta property="og:description" content="Enterprise AI, ERP and digital solutions by ARDS."/><meta property="og:image" content="https://ards.in/logo.png"/><link rel="canonical" href="https://ards.in/"/><script type="application/ld+json">{JSON.stringify({'@context':'https://schema.org','@type':'ProfessionalService',name:'Alpenrose Digital Solutions',url:'https://ards.in',areaServed:'India',address:{'@type':'PostalAddress',addressLocality:'Patna',addressRegion:'Bihar',addressCountry:'IN'},telephone:'+91-9308579699'})}</script></Helmet>
  <CinematicHero />
  {/* Legacy hero retained below is hidden to preserve existing markup during rollout. */}<section className="hero legacy-hero" id="home"><div className="hero-glow one"/><div className="hero-glow two"/><div className="site-shell hero-grid">
   <motion.div className="hero-copy" initial={{opacity:0,x:-30}} animate={{opacity:1,x:0}} transition={{duration:.7}}><div className="eyebrow-pill"><Icons.Sparkles size={16}/> AI-first digital transformation partner</div><h1>Transform Your Business With <span>Intelligent Digital Solutions.</span></h1><p>We help educational institutions, hospitals, enterprises, manufacturers, government organizations and businesses automate operations using AI, ERP, mobile apps, cloud solutions and custom software.</p><div className="hero-actions"><Link className="btn btn-primary magnetic" to="/contact">Book Free Demo <Icons.ArrowUpRight/></Link><a className="btn btn-secondary" href="#solutions">Explore Solutions <Icons.ArrowDown/></a><a className="watch-link" href="#live-demo"><span><Icons.Play/></span> Watch Demo</a></div><div className="trust-row"><span><Icons.ShieldCheck/> Secure by design</span><span><Icon name="CheckCircle2"/> Built for India</span><span><Icons.Headphones/> Human support</span></div></motion.div>
   <motion.div className="hero-art" initial={{opacity:0,scale:.92}} animate={{opacity:1,scale:1}} transition={{duration:.9,delay:.15}}><img src={heroVisual} alt="ARDS enterprise analytics, ERP, AI and cloud solutions dashboard" fetchPriority="high"/><div className="float-chip ai"><Icons.Bot/> AI Automation</div><div className="float-chip up"><Icons.TrendingUp/> +38% efficiency</div></motion.div>
  </div><div className="site-shell hero-stats">{[['500+','Projects delivered'],['20+','Solutions'],['99.9%','Uptime'],['24×7','Support']].map(x=><div key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div></section>

  <section className="logo-strip"><span>Trusted technology for ambitious organizations</span><div>{['EDUCATION','HEALTHCARE','GOVERNMENT','MANUFACTURING','RETAIL'].map(x=><b key={x}>{x}</b>)}</div></section>

  <section className="section" id="solutions"><div className="site-shell"><Heading eyebrow="Capabilities" title="One partner. Every digital capability." copy="Strategy, design and engineering come together to solve your toughest operational challenges."/><div className="service-grid">{(showAllServices?services:services.slice(0,8)).map(([t,i,d],n)=><Reveal key={t}><Link className="service-card" to={servicePath(t)}><div className="icon-box"><Icon name={i}/></div><small>{String(n+1).padStart(2,'0')}</small><h3>{t}</h3><p>{d}</p><span className="service-card-more">Learn more <Icons.ArrowRight/></span></Link></Reveal>)}</div><div className="capabilities-toggle"><button className="btn btn-secondary" type="button" onClick={()=>setShowAllServices(value=>!value)}>{showAllServices?'Show fewer capabilities':'Show all capabilities'} {showAllServices?<Icons.ChevronUp/>:<Icons.ChevronDown/>}</button></div></div></section>

  <section className="section soft-section"><div className="site-shell"><Heading eyebrow="Industries" title="Deep context. Better outcomes." copy="Purpose-built digital experiences for organizations that keep the world moving."/><div className="industry-grid">{industries.map(([t,i])=><Link className="industry-card" to={industryPath(t)} key={t}><span><Icon name={i} size={25}/></span><h3>{t}</h3><Icons.ArrowUpRight/></Link>)}</div></div></section>

  <section className="section dark-section"><div className="site-shell split"><Reveal className="ai-visual"><div className="ai-orbit"><div className="brain"><Icon name="BrainCircuit" size={70}/></div>{['ScanFace','Workflow','BarChart3','Bot'].map((name,i)=><span style={{'--i':i}} key={name}><Icon name={name}/></span>)}</div></Reveal><div><Heading eyebrow="ARDS Intelligence" title="Work smarter with AI" copy="Give your team intelligent tools that see patterns, automate decisions and turn documents into action."/><div className="feature-list">{aiFeatures.map(([t,i])=><div key={t}><Icon name={i}/><span>{t}</span></div>)}</div><Link className="btn btn-light" to="/ai-solutions">Explore AI solutions <Icons.ArrowRight/></Link></div></div></section>

  <EnterpriseERP />

  <section className="section soft-section"><div className="site-shell"><Heading eyebrow="Why ARDS" title="Enterprise discipline. Startup speed."/><div className="why-grid">{why.map(([t,i])=><div key={t}><span><Icon name={i}/></span><h3>{t}</h3><p>Practical expertise, transparent delivery and outcomes you can measure.</p></div>)}</div></div></section>

  <section className="section"><div className="site-shell"><Heading eyebrow="Our process" title="From idea to impact, without the guesswork."/><div className="process">{['Discovery','Planning','Design','Development','Testing','Deployment','Support'].map((x,i)=><div key={x}><b>{String(i+1).padStart(2,'0')}</b><span/><h3>{x}</h3></div>)}</div></div></section>

  <section className="section automation-story"><div className="site-shell"><Heading eyebrow="Business automation" title="From operational chaos to one clear view." copy="We connect scattered work into a system that runs, measures and improves itself."/><div className="transform-board"><motion.div className="before-panel" whileHover={{y:-5}}><span className="panel-label bad">BEFORE AUTOMATION</span><h3>Busy teams. Invisible progress.</h3><div className="chaos-list">{[['Paper files','Files'],['Disconnected Excel sheets','Table2'],['Manual attendance','ClipboardCheck'],['Endless phone follow-ups','PhoneCall'],['Daily operational stress','CircleAlert']].map(([x,i])=><div key={x}><Icon name={i}/><span>{x}</span><Icons.X/></div>)}</div></motion.div><div className="flow-arrow"><span><Icons.ArrowRight/></span><small>ARDS FLOW</small></div><motion.div className="after-panel" whileHover={{y:-5}}><span className="panel-label good">AFTER AUTOMATION</span><div className="smart-head"><div><small>Good morning</small><h3>Everything is on track.</h3></div><span><Icons.Bell/></span></div><div className="smart-stats"><div><Icon name="Workflow"/><b>84%</b><small>Automated</small></div><div><Icon name="Clock3"/><b>42h</b><small>Saved</small></div><div><Icon name="CheckCircle2"/><b>98%</b><small>On time</small></div></div><div className="smart-graph">{[42,60,48,75,67,88,82,96].map((h,i)=><i style={{height:h+'%'}} key={i}/>)}</div><div className="success-line"><Icons.CheckCircle2/> Weekly reports generated automatically</div></motion.div></div></div></section>

  <section className="section live-demo" id="live-demo"><div className="site-shell"><Heading eyebrow="Live product experience" title="Don’t take our word for it. Try the workflow." copy="Explore a lightweight simulation of the connected experiences we build."/><div className="demo-tabs">{['Attendance','Analytics','AI Assistant'].map(x=><button className={demo===x?'active':''} onClick={()=>setDemo(x)} key={x}>{x}</button>)}</div><div className="demo-stage">{demo==='Attendance'&&<motion.div key="attendance" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="attendance-demo"><div className="face-scan"><Icons.ScanFace/><span/><small>Identity verified</small></div><div className="employee-card"><span>AK</span><div><h3>Ananya Kumari</h3><p>Product Design · Patna Office</p></div><b><Icons.Check/> Checked in · 09:12</b></div></motion.div>}{demo==='Analytics'&&<motion.div key="analytics" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="analytics-demo"><div className="analytic-kpis"><div><span>Revenue</span><b>₹24.8L</b><em>↑ 18.4%</em></div><div><span>Efficiency</span><b>91.2%</b><em>↑ 7.1%</em></div><div><span>Open tasks</span><b>128</b><em>↓ 12.2%</em></div></div><div className="line-chart"><svg viewBox="0 0 700 180" preserveAspectRatio="none"><path d="M0,145 C80,120 110,150 180,110 S280,80 350,92 S460,35 520,58 S630,24 700,18"/><path className="fill" d="M0,145 C80,120 110,150 180,110 S280,80 350,92 S460,35 520,58 S630,24 700,18 L700,180 L0,180Z"/></svg></div></motion.div>}{demo==='AI Assistant'&&<motion.div key="ai" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="chat-demo"><div className="chat-title"><span><Icons.Bot/></span><div><h3>ARDS Intelligence</h3><small>Online · Your business copilot</small></div></div><div className="chat-bubble user">Summarize pending approvals and flag anything urgent.</div><div className="chat-bubble bot"><Icons.Sparkles/><p>You have <b>12 pending approvals</b>. Three purchase requests exceed their department budgets and need attention today. I’ve prepared a detailed report.</p></div><div className="chat-input">Ask about your business data… <Icons.Send/></div></motion.div>}</div></div></section>

  <section className="section case-section"><div className="site-shell"><Heading eyebrow="Selected transformations" title="Proof lives in the outcome."/><div className="case-grid">{[['Education ERP','80%','faster fee reconciliation','Building a connected campus'],['AI Attendance','95%','less manual processing','Making every check-in accurate'],['Workflow Automation','42 hrs','saved every month','Turning approval delays into flow']].map((c,i)=><article key={c[0]}><div className={'case-art c'+i}><Icon name={i===0?'GraduationCap':i===1?'ScanFace':'Workflow'} size={44}/></div><span>CASE STUDY · {c[0]}</span><h3>{c[3]}</h3><div><strong>{c[1]}</strong><p>{c[2]}</p></div><Link to="/work">View case study <Icons.ArrowUpRight/></Link></article>)}</div></div></section>

  <section className="section roi-section" id="roi"><div className="site-shell roi"><div><Heading eyebrow="ROI calculator" title="What could automation give back to your team?" copy="Move the sliders for an instant directional estimate based on your current manual effort."/><div className="slider-row"><label><span>Employees doing repetitive work</span><b>{employees}</b></label><input type="range" min="5" max="250" value={employees} onChange={e=>setEmployees(+e.target.value)}/></div><div className="slider-row"><label><span>Hours spent per person / month</span><b>{hours}h</b></label><input type="range" min="1" max="40" value={hours} onChange={e=>setHours(+e.target.value)}/></div></div><div className="roi-result"><span>Estimated monthly savings</span><strong>₹{monthly.toLocaleString('en-IN')}</strong><p>≈ {(employees*hours*.65).toFixed(0)} productive hours recovered</p><Link className="btn btn-primary" to="/contact">Get a tailored ROI report <Icons.ArrowRight/></Link><small>*Illustrative estimate using ₹250/hour and 65% automation potential.</small></div></div></section>

  <section className="section"><div className="site-shell"><Heading eyebrow="Technology" title="Modern foundations. No lock-in."/><div className="stack">{stack.map(x=><span key={x}>{x}</span>)}</div><div className="big-stats">{[['50+','Projects'],['50+','Happy clients'],['20+','Solutions'],['10+','Industries'],['100%','Uptime']].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div></div></section>

  <section className="section testimonials"><div className="site-shell"><Heading eyebrow="Client stories" title="Trusted where execution matters."/><div className="quote-grid">{[['“ARDS understood our operations before writing a single line of code. The result feels built for us.”','Operations Director','Education Group'],['“We replaced scattered spreadsheets with one reliable view. Decisions are faster and the team is happier.”','Chief Administrator','Healthcare Network'],['“The automation paid for itself far sooner than expected. Support continues to be excellent.”','Managing Director','Manufacturing Company']].map(q=><blockquote key={q[1]}><div>★★★★★</div><p>{q[0]}</p><footer><span>{q[1]}</span><small>{q[2]}</small></footer></blockquote>)}</div><div className="google-review-row"><div><Icons.Star/><span><b>Worked with ARDS?</b><small>Share your experience on our verified Google Business profile.</small></span></div><a href="https://share.google/Nqbo2IjNtnMrnU4ZI" target="_blank" rel="noopener noreferrer">Review us on Google <Icons.ExternalLink/></a></div></div></section>

  <section className="section"><div className="site-shell faq"><Heading eyebrow="FAQ" title="Questions, answered."/><div>{[['What kinds of organizations does ARDS work with?','We partner with startups, growing businesses, institutions and government organizations across India.'],['Can ARDS customize an ERP for our workflow?','Yes. We map your process first, configure the right modules and build custom integrations where they create value.'],['How quickly can a project launch?','A focused website can launch in weeks; larger ERP and automation programs are delivered in clear, usable phases.'],['Do you provide post-launch support?','Yes. Monitoring, updates, training and 24×7 support plans keep your solution healthy after launch.'],['Is our business data secure?','We apply role-based access, encryption, secure cloud architecture, backups and audit-ready engineering practices.']].map((x,i)=><div className="faq-item" key={x[0]}><button onClick={()=>setOpenFaq(openFaq===i?-1:i)} aria-expanded={openFaq===i}><span>{x[0]}</span>{openFaq===i?<Icons.Minus/>:<Icons.Plus/>}</button>{openFaq===i&&<motion.p initial={{opacity:0}} animate={{opacity:1}}>{x[1]}</motion.p>}</div>)}</div></div></section>

  <section className="section soft-section"><div className="site-shell"><Heading eyebrow="Insights" title="Ideas for the next way of working."/><div className="blog-grid">{[['AI','AI automation: where should your business begin?','A practical roadmap for finding fast, low-risk wins.'],['ERP','The hidden cost of disconnected business software','Why one source of truth changes more than reporting.'],['Growth','How better digital experiences compound growth','Turn every customer interaction into useful momentum.']].map((x,i)=><article key={x[1]}><div className={'blog-cover b'+i}><span>{x[0]}</span></div><small>6 MIN READ</small><h3>{x[1]}</h3><p>{x[2]}</p><Link to="/blog">Read article <Icons.ArrowRight/></Link></article>)}</div></div></section>

  <section className="final-cta"><div className="site-shell"><span>YOUR NEXT ADVANTAGE STARTS HERE</span><h2>Ready to make work<br/>work better?</h2><p>Let’s find the simplest path from manual effort to measurable growth.</p><div><Link className="btn btn-light" to="/contact">Book your free demo <Icons.ArrowUpRight/></Link><a href="tel:+919308579699" className="phone-link"><Icons.Phone/> +91 93085 79699</a></div></div></section>
 </>;
}
