import React,{useState} from 'react';
import {Helmet} from 'react-helmet';
import {Link} from 'react-router-dom';
import {AnimatePresence,motion} from 'framer-motion';
import * as I from 'lucide-react';
import systemFlow from '@/assets/case-studies-system-flow.png';
import educationVisual from '@/assets/work-education-erp.png';
import aiAttendanceVisual from '@/assets/work-ai-attendance.png';
import manufacturingVisual from '@/assets/work-manufacturing-erp.png';
import healthcareVisual from '@/assets/work-healthcare-erp.png';
import financeAutomationVisual from '@/assets/work-finance-automation.png';
import webMobileVisual from '@/assets/work-web-mobile-platform.png';
import './CaseHeroFix.css';

const studies=[
 {category:'Education',tag:'ERP · AUTOMATION',title:'A government college becomes one connected digital campus.',summary:'Admissions, student records, hostel operations and reporting moved from fragmented paper workflows to one secure platform.',icon:'GraduationCap',image:educationVisual,color:'blue',metric:'80%',metricLabel:'less administrative work',before:['Paper admission records','Disconnected student data','Slow departmental reporting'],after:['Unified student lifecycle','Role-based dashboards','Real-time institutional reports'],results:[['3K+','students supported'],['42 hrs','saved weekly'],['99.8%','record accuracy']]},
 {category:'AI',tag:'AI · ATTENDANCE',title:'Face recognition removes queues and proxy attendance.',summary:'A high-volume facility replaced manual registers with fast, touch-free identity verification and live attendance intelligence.',icon:'ScanFace',image:aiAttendanceVisual,color:'violet',metric:'95%',metricLabel:'faster daily processing',before:['Manual register entries','Proxy attendance risk','End-of-month reconciliation'],after:['Instant face verification','Live attendance status','Automated payroll export'],results:[['<1 sec','verification'],['0','proxy entries'],['18 hrs','saved monthly']]},
 {category:'Healthcare',tag:'ERP · HEALTHCARE',title:'Hospital operations shift from silos to coordinated care.',summary:'Patient administration, billing, pharmacy and inventory were connected without disrupting frontline clinical workflows.',icon:'HeartPulse',image:healthcareVisual,color:'pink',metric:'38%',metricLabel:'faster patient processing',before:['Repeated data entry','Billing bottlenecks','Poor stock visibility'],after:['One patient record','Connected billing flow','Live pharmacy stock'],results:[['32%','fewer delays'],['24×7','system access'],['1 view','for leadership']]},
 {category:'Manufacturing',tag:'ERP · MANUFACTURING',title:'Production leaders gain a live view from material to dispatch.',summary:'Planning, purchases, inventory, quality and dispatch now operate through one source of truth built around the factory floor.',icon:'Factory',image:manufacturingVisual,color:'green',metric:'24%',metricLabel:'lower inventory leakage',before:['Spreadsheet production plans','Unknown material variance','Delayed dispatch updates'],after:['Live production status','Material traceability','Automated dispatch alerts'],results:[['17%','faster cycles'],['24%','less leakage'],['100%','batch traceability']]},
 {category:'Automation',tag:'WORKFLOW · FINANCE',title:'Approvals that took days now move in hours.',summary:'A growing enterprise standardized purchase and finance approvals with intelligent routing, reminders and escalation rules.',icon:'Workflow',image:financeAutomationVisual,color:'orange',metric:'72%',metricLabel:'shorter approval time',before:['Email and phone follow-ups','Missing approval context','No audit trail'],after:['Rule-based routing','Smart notifications','Complete decision history'],results:[['72%','faster approvals'],['42 hrs','saved monthly'],['100%','audit visibility']]},
 {category:'Web & Apps',tag:'WEB · MOBILE',title:'A fragmented customer journey becomes one conversion engine.',summary:'A responsive web platform and mobile experience connected discovery, service requests, payments and support.',icon:'PanelsTopLeft',image:webMobileVisual,color:'cyan',metric:'2.4×',metricLabel:'more qualified enquiries',before:['Slow legacy website','Manual lead handoff','No journey analytics'],after:['Fast product experience','CRM-connected leads','Conversion intelligence'],results:[['91','Lighthouse score'],['2.4×','qualified leads'],['41%','lower bounce']]}
];
const filters=['All','Education','AI','Healthcare','Manufacturing','Automation','Web & Apps'];
const SafeIcon=({name,size=24})=>{const C=I[name]||I.Sparkles;return <C size={size}/>};

export default function OurWorkPage(){const [filter,setFilter]=useState('All');const [active,setActive]=useState(0);const visible=filter==='All'?studies:studies.filter(x=>x.category===filter);return <>
 <Helmet><title>Selected Work | ARDS</title><meta name="description" content="Selected ERP, AI, healthcare, manufacturing and application projects with measurable outcomes."/><link rel="canonical" href="https://ards.in/work"/></Helmet>
 <section className="case-hero visual-first"><div className="case-grid-bg"/><div className="case-orb one"/><div className="case-orb two"/><div className="site-shell"><motion.div className="case-hero-copy" initial={{opacity:0,y:25}} animate={{opacity:1,y:0}}><span className="case-kicker"><I.Sparkles/> SELECTED WORK</span><h1>From friction<br/>to <em>flow.</em></h1><p>Six systems. Six clear outcomes.</p><div className="case-hero-actions"><a href="#case-library" className="btn btn-light">View projects <I.ArrowDown/></a><Link to="/contact" className="case-text-link">Discuss a project <I.ArrowUpRight/></Link></div></motion.div><motion.div className="case-hero-graphic" initial={{opacity:0,scale:.96,x:40}} animate={{opacity:1,scale:1,x:0}} transition={{duration:.9}}><img src={systemFlow} alt="Manual processes flowing into an organized digital system"/><div className="graphic-label left"><I.Files/> Manual</div><div className="graphic-label right"><I.Sparkles/> Connected</div></motion.div><div className="proof-ribbon">{[['80%','Admin time'],['<1 sec','AI check-in'],['24%','Less leakage'],['2.4×','More enquiries']].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div></div></section>

 <section className="section featured-case"><div className="site-shell"><div className="featured-label"><span>FEATURED CASE STUDY</span><b>01 / 06</b></div><div className="featured-layout"><motion.div className="featured-copy" initial={{opacity:0,x:-20}} whileInView={{opacity:1,x:0}} viewport={{once:true}}><div className="study-tag">EDUCATION · ENTERPRISE ERP</div><h2>From paper-heavy administration to a connected digital campus.</h2><p>A government institution needed more than another website. It needed a dependable operating layer for admissions, records, hostel workflows and decision-ready reporting.</p><div className="featured-outcome"><strong>80%</strong><span>reduction in repetitive<br/>administrative work</span></div><Link to="/contact">Build a similar solution <I.ArrowRight/></Link></motion.div><motion.div className="campus-dashboard" initial={{opacity:0,scale:.94}} whileInView={{opacity:1,scale:1}} viewport={{once:true}}><div className="dash-chrome"><i/><i/><i/><span>ARDS CAMPUS OS</span></div><div className="dash-layout"><aside><b>A</b>{[I.LayoutDashboard,I.Users,I.GraduationCap,I.WalletCards,I.BarChart3].map((C,i)=><C key={i}/>)}</aside><main><div className="dash-welcome"><div><small>OVERVIEW</small><h3>Good morning, Admin</h3></div><button><I.Download/> Report</button></div><div className="dash-cards"><div><span>Total students</span><b>3,248</b><em>+8.4%</em></div><div><span>Attendance today</span><b>92.8%</b><em>Live</em></div><div><span>Fees collected</span><b>₹18.4L</b><em>+12%</em></div></div><div className="dash-bottom"><div className="area-chart"><span>Campus activity</span><svg viewBox="0 0 500 150"><path d="M0 128 C55 110 70 130 115 90 S195 112 240 68 S320 88 360 45 S430 64 500 20"/></svg></div><div className="task-ring"><span>Completed</span><b>84%</b><i/></div></div></main></div></motion.div></div></div></section>

 <section className="section case-library" id="case-library"><div className="site-shell"><div className="case-library-head"><div><span>THE WORK</span><h2>Transformation, by challenge.</h2></div><div className="case-filters">{filters.map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div></div><motion.div layout className="study-grid"><AnimatePresence mode="popLayout">{visible.map((s,index)=><motion.article layout initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:.96}} transition={{duration:.3}} key={s.title} className={'study-card '+s.color}><div className={'study-visual '+(s.image?'has-image':'')}>{s.image&&<img src={s.image} alt={`${s.category} digital transformation solution by ARDS`} loading="lazy"/>}<div className="study-icon"><SafeIcon name={s.icon} size={34}/></div><div className="metric-float"><strong>{s.metric}</strong><span>{s.metricLabel}</span></div>{!s.image&&<div className="visual-lines"><i/><i/><i/></div>}</div><div className="study-content"><span>{s.tag}</span><h3>{s.title}</h3><p>{s.summary}</p><button onClick={()=>setActive(studies.indexOf(s))}>Explore transformation <I.ArrowUpRight/></button></div></motion.article>)}</AnimatePresence></motion.div></div></section>

 <section className="section transformation-detail"><div className="site-shell"><div className="detail-heading"><span>INSIDE THE TRANSFORMATION</span><h2>{studies[active].title}</h2><div className="detail-nav"><button onClick={()=>setActive((active-1+studies.length)%studies.length)} aria-label="Previous"><I.ArrowLeft/></button><span>{String(active+1).padStart(2,'0')} / {String(studies.length).padStart(2,'0')}</span><button onClick={()=>setActive((active+1)%studies.length)} aria-label="Next"><I.ArrowRight/></button></div></div><AnimatePresence mode="wait"><motion.div className="before-after" key={active} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}}><div className="state before"><span><I.X/> BEFORE ARDS</span>{studies[active].before.map(x=><div key={x}><I.CircleDashed/><p>{x}</p></div>)}</div><div className="transformation-core"><div><SafeIcon name={studies[active].icon} size={40}/></div><span>DESIGNED<br/>BY ARDS</span><I.ArrowRight/></div><div className="state after"><span><I.Check/> AFTER ARDS</span>{studies[active].after.map(x=><div key={x}><I.CheckCircle2/><p>{x}</p></div>)}</div></motion.div></AnimatePresence><div className="result-strip">{studies[active].results.map(([v,l])=><div key={l}><b>{v}</b><span>{l}</span></div>)}</div></div></section>

 <section className="section approach-section"><div className="site-shell"><div className="approach-copy"><span>HOW WE CREATE THE SHIFT</span><h2>No theatre.<br/>Just a clear path to value.</h2><p>We begin with the operational reality, design the smallest effective system and improve it with evidence from real use.</p></div><div className="approach-steps">{[['01','Diagnose','Find the friction, cost and opportunity.'],['02','Design','Shape the workflow and experience together.'],['03','Deliver','Launch usable value in focused phases.'],['04','Improve','Measure, learn and compound the gains.']].map(([n,t,p])=><div key={n}><b>{n}</b><span><h3>{t}</h3><p>{p}</p></span><I.ArrowDownRight/></div>)}</div></div></section>

 <section className="case-cta"><div className="site-shell"><motion.div initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><span>YOUR BUSINESS, NEXT</span><h2>What could your<br/>before and after look like?</h2><p>Bring us one stubborn workflow. We’ll show you the clearest route to making it better.</p><div><Link to="/contact" className="btn btn-light">Book a free discovery call <I.ArrowUpRight/></Link><a href="https://wa.me/919308579699" className="case-whatsapp"><I.MessageCircle/> Talk on WhatsApp</a></div></motion.div></div></section>
 </>}
