import React,{useState} from 'react';
import {Helmet} from 'react-helmet';
import {Link} from 'react-router-dom';
import {AnimatePresence,motion} from 'framer-motion';
import * as I from 'lucide-react';
import './ServicesPage.css';

const solutions={
 'AI & Automation':{icon:'BrainCircuit',eyebrow:'INTELLIGENCE LAYER',title:'Turn repetitive work into intelligent flow.',copy:'AI that reads, recognizes, responds and acts across daily operations.',color:'violet',items:[['AI Automation','Workflow'],['Face Recognition','ScanFace'],['Chatbots','Bot'],['OCR Processing','ScanText'],['Predictive Analytics','BarChart3'],['Smart Reporting','FileBarChart']]},
 'ERP Platforms':{icon:'Blocks',eyebrow:'ONE OPERATING SYSTEM',title:'Connect every department and decision.',copy:'Modular platforms shaped around real institutional and enterprise workflows.',color:'blue',items:[['Education ERP','GraduationCap'],['Hospital ERP','HeartPulse'],['Manufacturing ERP','Factory'],['HRMS & Payroll','Users'],['Inventory','Boxes'],['Finance & CRM','WalletCards']]},
 'Web & Apps':{icon:'PanelsTopLeft',eyebrow:'DIGITAL EXPERIENCES',title:'Products people understand instantly.',copy:'Fast, accessible experiences for customers, employees and partners.',color:'pink',items:[['Corporate Websites','Globe2'],['Web Applications','AppWindow'],['Android & iOS','Smartphone'],['Flutter Apps','Layers3'],['E-Commerce','ShoppingBag'],['Customer Portals','Contact']]},
 'Cloud & Security':{icon:'CloudCog',eyebrow:'RESILIENT FOUNDATIONS',title:'Infrastructure ready for the next stage.',copy:'Secure cloud environments engineered for performance, continuity and scale.',color:'cyan',items:[['Cloud Migration','CloudUpload'],['AWS & Azure','Cloud'],['DevOps','GitBranch'],['Managed Hosting','Server'],['Cyber Security','ShieldCheck'],['Backup & Recovery','DatabaseBackup']]},
 'Growth Systems':{icon:'TrendingUp',eyebrow:'COMPOUNDING GROWTH',title:'Make every digital interaction measurable.',copy:'Strategy, creative and analytics connected to qualified demand.',color:'orange',items:[['Search Optimization','Search'],['Performance Marketing','Megaphone'],['Brand Systems','Gem'],['Content Marketing','FileText'],['Conversion UX','MousePointerClick'],['Growth Analytics','ChartNoAxesCombined']]}
};
const categories=Object.keys(solutions);
const SafeIcon=({name,size=22})=>{const C=I[name]||I.Sparkles;return <C size={size}/>};
const reveal={initial:{opacity:0,y:24},whileInView:{opacity:1,y:0},viewport:{once:true,margin:'-70px'},transition:{duration:.55,ease:[.22,1,.36,1]}};

export default function ServicesPage(){const [active,setActive]=useState(categories[0]);const current=solutions[active];return <>
 <Helmet><title>AI, ERP, Cloud & Software Solutions | ARDS</title><meta name="description" content="Explore AI automation, ERP platforms, web and mobile applications, cloud infrastructure, cyber security and growth solutions from ARDS."/><link rel="canonical" href="https://ards.in/services"/></Helmet>
 <section className="solutions-hero"><div className="solutions-grid-bg"/><div className="solution-aura sa-one"/><div className="solution-aura sa-two"/><div className="site-shell solutions-hero-layout"><motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}}><span className="solutions-kicker"><i/> SOLUTIONS BUILT AROUND OUTCOMES</span><h1>One partner.<br/><em>Every digital layer.</em></h1><p>From the first workflow to the full operating platform.</p><div className="solutions-actions"><Link to="/contact" className="btn btn-primary">Discuss your project <I.ArrowUpRight/></Link><a href="#solution-explorer" className="btn btn-secondary">Explore capabilities <I.ArrowDown/></a></div><div className="solutions-proof"><span><I.CheckCircle2/> Modular by design</span><span><I.ShieldCheck/> Enterprise security</span><span><I.Expand/> Built to scale</span></div></motion.div><motion.div className="solution-orbit" initial={{opacity:0,scale:.9}} animate={{opacity:1,scale:1}} transition={{duration:.8}}><div className="orbit-track outer"/><div className="orbit-track inner"/><div className="orbit-center"><span>ARDS</span><b>Digital<br/>Core</b><i/></div>{categories.map((x,index)=>{const s=solutions[x];return <motion.button key={x} className={'orbit-solution os-'+index} onClick={()=>setActive(x)} animate={{y:[0,index%2?8:-8,0]}} transition={{duration:4+index*.35,repeat:Infinity}}><span><SafeIcon name={s.icon}/></span><div><b>{x}</b><small>{s.eyebrow}</small></div></motion.button>})}<div className="orbit-pulse p1"/><div className="orbit-pulse p2"/></motion.div></div></section>

 <section className="section solution-explorer" id="solution-explorer"><div className="site-shell"><motion.div className="solution-heading" {...reveal}><span>CAPABILITY EXPLORER</span><h2>Start with the challenge,<br/>not the technology.</h2></motion.div><div className="solution-tabs" role="tablist">{categories.map(x=><button key={x} className={active===x?'active':''} onClick={()=>setActive(x)} role="tab" aria-selected={active===x}><SafeIcon name={solutions[x].icon}/><span>{x}</span></button>)}</div><AnimatePresence mode="wait"><motion.div className={'solution-feature '+current.color} key={active} initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-15}} transition={{duration:.35}}><div className="feature-copy"><span>{current.eyebrow}</span><h2>{current.title}</h2><p>{current.copy}</p><Link to={active==='AI & Automation'?'/ai-solutions':active==='ERP Platforms'?'/business-automation':'/contact'}>Explore {active} <I.ArrowRight/></Link></div><div className="feature-modules">{current.items.map(([name,icon],index)=><motion.div key={name} initial={{opacity:0,scale:.94}} animate={{opacity:1,scale:1}} transition={{delay:index*.05}}><span><SafeIcon name={icon}/></span><b>{name}</b><small>Learn more</small><I.ArrowUpRight/></motion.div>)}</div></motion.div></AnimatePresence></div></section>

 <section className="section architecture-section"><div className="site-shell"><motion.div className="architecture-copy" {...reveal}><span>CONNECTED BY DESIGN</span><h2>Not a collection of tools.<br/>One coherent system.</h2><p>Information moves cleanly between customer experiences, operations, intelligence and infrastructure.</p></motion.div><motion.div className="architecture-map" {...reveal}><div className="arch-core"><SafeIcon name="Sparkles" size={30}/><b>Intelligence</b></div>{[['Experience','PanelsTopLeft','a1'],['Operations','Workflow','a2'],['Data','Database','a3'],['Cloud','Cloud','a4'],['Security','ShieldCheck','a5'],['Growth','TrendingUp','a6']].map(([name,icon,cls])=><div className={'arch-node '+cls} key={name}><span><SafeIcon name={icon}/></span><b>{name}</b></div>)}<svg viewBox="0 0 700 420"><g>{[[350,210,105,80],[350,210,350,35],[350,210,595,80],[350,210,105,340],[350,210,350,385],[350,210,595,340]].map((p,i)=><path key={i} d={`M${p[0]} ${p[1]} C${(p[0]+p[2])/2} ${p[1]}, ${(p[0]+p[2])/2} ${p[3]}, ${p[2]} ${p[3]}`}/>)}</g></svg></motion.div></div></section>

 <section className="section engagement-section"><div className="site-shell"><motion.div className="solution-heading" {...reveal}><span>WAYS TO WORK TOGETHER</span><h2>Choose the right starting point.</h2></motion.div><div className="engagement-grid">{[['01','Focused Build','A defined product, portal, website or automation delivered end to end.','Rocket'],['02','Platform Program','A phased ERP or digital platform with clear releases and adoption support.','Layers3'],['03','Embedded Team','Product, design and engineering capacity integrated with your team.','Users'],['04','Modernization','Upgrade a legacy system without interrupting critical operations.','RefreshCw']].map(([n,title,copy,icon],i)=><motion.article key={title} {...reveal} transition={{...reveal.transition,delay:i*.07}}><small>{n}</small><span><SafeIcon name={icon}/></span><h3>{title}</h3><p>{copy}</p><Link to="/contact">Talk to us <I.ArrowRight/></Link></motion.article>)}</div></div></section>

 <section className="solution-stack"><div className="site-shell"><span>ENGINEERED WITH</span><div>{['React','Next.js','Python','FastAPI','Node.js','Flutter','PostgreSQL','Docker','AWS','Azure','TensorFlow','OpenCV'].map(x=><b key={x}>{x}</b>)}</div></div></section>
 <section className="solutions-cta"><div className="site-shell"><motion.div {...reveal}><span>YOUR NEXT SYSTEM</span><h2>What should work<br/>better tomorrow?</h2><p>Bring the workflow, bottleneck or idea. We’ll help define the clearest next move.</p><div><Link to="/contact" className="btn btn-primary">Book a free consultation <I.ArrowUpRight/></Link><a href="tel:+919308579699"><I.Phone/> +91 93085 79699</a></div></motion.div></div></section>
 </>}
