import React from 'react';
import {Helmet} from 'react-helmet';
import {Link} from 'react-router-dom';
import {motion} from 'framer-motion';
import * as I from 'lucide-react';

const data={ai:{eyebrow:'ARTIFICIAL INTELLIGENCE',title:'AI that moves work forward.',copy:'Practical AI solutions that understand documents, recognize patterns, support teams and surface better decisions.',items:[['AI Chatbots','Bot'],['Face Recognition','ScanFace'],['OCR & Document Processing','ScanText'],['Predictive Analytics','BarChart3'],['AI Dashboards','LayoutDashboard'],['Smart Reporting','FileBarChart']]},automation:{eyebrow:'BUSINESS AUTOMATION',title:'Less busywork. More business.',copy:'Connect people, processes and data with systems designed around the way your organization actually works.',items:[['Office Management System','Building2'],['Attendance Management','ScanFace'],['Visitor Management','Contact'],['Asset Management','PackageCheck'],['Helpdesk & Ticketing','Ticket'],['CRM','Users'],['Sales Automation','TrendingUp'],['Purchase Management','ShoppingCart'],['Finance & Billing','Receipt'],['Workflow Automation','Workflow']]}};
const SafeIcon=({name})=>{const C=I[name]||I.Sparkles;return <C/>};

export default function SolutionLanding({type='ai'}){const d=data[type]||data.ai;return <><Helmet><title>{d.title} | ARDS</title><meta name="description" content={d.copy}/></Helmet><section className="sub-hero"><div className="site-shell"><span>{d.eyebrow}</span><h1>{d.title}</h1><p>{d.copy}</p><Link to="/contact" className="btn btn-primary">Book Free Demo <I.ArrowUpRight/></Link></div></section><section className="section"><div className="site-shell solution-page-grid">{d.items.map(([x,icon],index)=><motion.article initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.04}} key={x}><span><SafeIcon name={icon}/></span><h2>{x}</h2><p>Secure, scalable and tailored to eliminate friction across your operations.</p><Link to="/contact">Talk to an expert <I.ArrowRight/></Link></motion.article>)}</div></section><section className="final-cta"><div className="site-shell"><span>START WITH ONE HIGH-IMPACT WORKFLOW</span><h2>See what smarter<br/>operations feel like.</h2><Link to="/contact" className="btn btn-light">Plan your solution <I.ArrowUpRight/></Link></div></section></>}
